### ISSUE TITLE
World global flag of group does not work.

### ISSUE THREAD

**Issue by de-shark** [Zrips/Residence#1001]
My flags.yml file:
```
Global:
  # These are world flags that are applied when the player is NOT within a residence.
  Flags:
    # these are default for all worlds unless specified below, they can be overridden per group
    Global:
      use: false
      build: false
      ignite: false
      firespread: false
      damage: false
      creeper: false
      tnt: false
      pvp: false
  ......
```
My groups.yml file:
```
    Vip:
       Flags:
          #these flags are applied specifically to this group whenever they are outside a residence
          #these flags will override the flags at the top, under the Global section.
          World:
                Global: #these flags will apply to all worlds
                     build: true
                WorldNameHere: #or you can apply them by each individual world
                     #build: false
```
I only listed the modified code, the other unmodified ones are not listed.
I have residence.group.vip permission, but I still can't build outside the territory.
Destory or place:
![image](https://user-images.githubusercontent.com/64623974/218473051-4dac7193-d788-4cb4-a5e6-5174afcdf6f6.png)
