### ISSUE TITLE
Unable to create territory

### ISSUE THREAD

**Issue by MCE-MatchaMC** [Zrips/Residence#1182]
Version Information
```
Paper version 1.20.6-134-master@4f13be9
Residence5.1.5.0.jar
```

config.yml
```
Selection:
    # By setting this to true, all selections will be made from bedrock to sky ignoring Y coordinates
    IgnoreY: true
    # When this set to true, selections inside existing residence will be from bottom to top of that residence
    # When this set to false, selections inside existing residence will be exactly as they are
    IgnoreYInSubzone: true
    # Defines height of nether when creating residences. This mostly applies when performing commands like /res select vert or /res auto which will expand residence to defined height
    # This cant be higher than 319 or lower than 1
    netherHeight: 319
    # By setting this to true, player will only pay for x*z blocks ignoring height
    # This will lower residence price by up to 319 times, so adjust block price BEFORE enabling this
    NoCostForYBlocks: true
    # Enable or disable world edit integration into Residence plugin
    WorldEditIntegration: true
```

Error
![螢幕擷取畫面 2024-06-06 223716](https://github.com/Zrips/Residence/assets/169152026/58138b51-bed5-4d32-8ae5-6f89b3c66adf)
