### ISSUE TITLE
Res auto size calculation is not working properly

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1235]
**Describe the bug**
I have groups, for example this one:

```
    hrabe: #group name, DONT remove this group
       # Information about the Residence zone that the player can define.
       #Uncomment the lines below to mirror this config to other groups.
       #Mirror:
         #- 'group1'
         #- 'group2'
       Residence:
           # Determins if this group can create residences or not.  This option can be overriden with the permissions node 'residence.create'
           CanCreate: true
           # The maximum number of Residences a player can have.
           MaxResidences: 3
           # The maximum number of physical areas a residence can have.
           MaxAreasPerResidence: 2
           # The maximum number of blocks a Residence can be, East to West (X).
           MaxEastWest: 160
           # (Optional) The minimum number of blocks a Residence can be, East to West (X).
           MinEastWest: 3
           # The maximum number of blocks a Residence can be, North to South (Z).
           MaxNorthSouth: 160
           # (Optional) The minimum number of blocks a Residence can be, North to South (Z).
           MinNorthSouth: 3
           # The maximum number of blocks a Residence can be, High to Low (Y).
           MaxUpDown: 384
           # (Optional) The minimum number of blocks a Residence can be, High to Low (Y).
           MinUpDown: 3
           # The lowest altitude this group is allowed to protect.
           MinHeight: -64
           # The highest altitude this group is allowed to protect.
           MaxHeight: 384
            # The maximum amount of subzones can current area have.
           MaxSubzonesInArea: 12
            # The maximum recursive depth that subzones can go.
            # A subzone within a subzone within the Residence zone would be a depth of 2.
            # Set to 0 to disable subzones.
           SubzoneDepth: 3
           # (Optional) The maximum number of blocks a Residence Subzone can be, East to West (X).
           SubzoneMaxEastWest: 64
           # (Optional) The minimum number of blocks a Residence Subzone can be, East to West (X).
           SubzoneMinEastWest: 3
           # (Optional) The maximum number of blocks a Residence Subzone can be, North to South (Z).
           SubzoneMaxNorthSouth: 64
           # (Optional) The minimum number of blocks a Residence Subzone can be, North to South (Z).
           SubzoneMinNorthSouth: 3
           # (Optional) The maximum number of blocks a Residence Subzone can be, High to Low (Y).
           SubzoneMaxUpDown: 384
           # (Optional) The minimum number of blocks a Residence Subzone can be, High to Low (Y).
           SubzoneMinUpDown: 3
           # Whether or not to allow teleporting to Residences.
           CanTeleport: true
           # Allow or Disallow the use of /res unstuck, to get yourself out of a residence if stuck in one somehow
           Unstuck: true
           # Allow or Disallow the use of /res kick, to kick player from residence.
           Kick: true
           # Allow or Disallow the use of the /res select command, if disabled they can only use the selection tool.
           SelectCommandAccess: true
           # Allow or Disallow the group to access the Blacklist/Ignorelist for residences they own.
           ItemListAccess: true
       # Options relating to enter and leave messages on the residence.
       Messaging:
           # Whether or not the player can change the Residence enter and leave messages.
           CanChange: true
           # The default enter message to apply to new Residences created by players in this group.
           # Use %zone if you want to include only current residence name without including parent zones into name
           # Leaving the message blank will disable it.
           DefaultEnter: "Vítej %player v residenci %residence, vlastněné hráčem %owner."
           # The default leave message to apply to new Residences created by players in this group.
           # Use %zone if you want to include only current residence name without including parent zones into name
           # Leaving the message blank will disable it.
           DefaultLeave: "Opouštíš residenci %residence."
       # Options relating to the Lease system.
       Lease:
          # The maximum number of days to allow leases.
          MaxDays: 16
          # The number of days to add to the lease following a '/res lease renew' command.
          RenewIncrement: 14
       #Options related to the rent system
       Rent:
           #determines how many residences can be rented by players of this group at once
           MaxRents: 3
           #determines how many residences can be set for rent by players of this group at once
           MaxRentables: 3
           # determines max days player can rent residence at once
           MaxRentDays: 31
       # Options relating to the Residence Economy.
       Economy:
          # Whether or not players in this group can buy other Residences that are for sale.
          CanBuy: true
          # Whether or not players in this group can sell their Residences.
          CanSell: true
          # Whether or not to ignore the Residence size/count limits when buying a residence.
          IgnoreLimits: false
          # The cost, per block, of making a new Residence or adding a area to it.
          BuyCost: 0.75
          # The cost, per block, player will be getting back when removing residence. 
          # ATTENTION ResMoneyBack needs to be enabled in config file for this to work
          SellCost: 0.25
          # The cost, per block, of renewing a Residence lease (if the lease system is enabled).
          RenewCost: 0.2
       # Flags are checked in the order:
       # 1: Player
       # 2: Group
       # 3: Owner
       # 4: If all others are undefined, reverts to default value (usually true).
       # Flag permissions default to false.
       # These flags settings override the globals.
       Flags:
          # Specifically allow or deny this group from changing certain flags.
          Permission:
               #build: true
          # Specifys the flags that are applied at residence creation for players of this group.
          Default:
              #build: true
          # Specifys the flags that are applied at to the creator at residence creation.
          CreatorDefault:
              #build: true
          # Specifys the flags that are applied to other groups for this residence, at creation.
          GroupDefault:
               #default: #group name
                   #build: false
          #these flags are applied specifically to this group whenever they are outside a residence
          #these flags will override the flags at the top, under the Global section.
          World:
                survival_nether: #or you can apply them by each individual world
                     move: true
                mobarena: #or you can apply them by each individual world
                     CanTeleport: false
                     chorustp: false
                     enderpearl: false
                     tp: false
                Pevnost: #or you can apply them by each individual world
                     CanTeleport: false
                     chorustp: false
                     enderpearl: false
                     tp: false
```
and in config:

```
    AutomaticResidenceCreation:
      # When set to true /res auto command will check for new area collision with other residences to avoid overlapping.
      # Set it to false to gain some performace but new residence can often overlap with old ones
      CheckCollision: true
      # Weird shaped residence detection when using automatic residence creation
      # This will inform player about residence shape being iregular cuboid before creation of it
      Ratio:
        Inform: true
        Confirmation: true
        # Defines value of ration when residence will be counted as weird shaped ones
        # Value of 3 will mean that one of the sides of cuboid is atleast 3 times bigger than one of the remaining ones
        Value: 3
      # Enabled this will switch to old method for calculating new residence area
      # Old method is allot less efficient, so its not recomended to be used when you have residence areas over 100
      OldMethod: false
      # Defines new residence name increment when using automatic residence creation command if residence with that name already exist
      IncrementFormat: _[number]
      Size:
        # When enabled we will try to create region by defined bounds
        Enabled: true
        # Value between 1 and 100 which will define size of residence we will create in percentage depending on players permission group
        Percentage: 40
        # Value in blocks. While previous percentage will determine general size, this can be used to avoid having tiny residences
        # For example if player has access to 30x30 residence and Percentage is set to 50% then instead of using 15 block size we will use 20 (default)
        # Keep in mind that this will not override actual max/min residence sizes player can have
        Min: 5
        # Value in blocks. While previous percentage will determine general size, this can be used to avoid having huge residences
        # For example if player has access to 500x500 residence and Percentage is set to 50% then instead of using 250 block size we will use 100 (default)
        # Keep in mind that this will not override actual max/min residence sizes player can have
        Max: 200

```

so the size should be 64, but, isnt. 

Instead of that, there is this error message:

![Image](https://github.com/user-attachments/assets/823b1d6b-8067-4d2f-b511-0640a098ea4f)

It says, that I cannot create residence with this size, but why?

**Server version:**

![Image](https://github.com/user-attachments/assets/deef0cc8-c68f-4090-838f-e5cd171f5dfd)
