### ISSUE TITLE
Teleport locations are not working properly

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1237]
**Describe the bug**
```
    KickLocation:
      # By setting this to true, when player kicks another player from residence, he will be teleported to this location instead of getting outside residence
      Use: true
      World: Pevnost
      X: 277
      Y: 103
      Z: 540
      # Less than 0 - head up, more than 0 - head down. Range from -90 to 90
      Pitch: 0.0
      # Head position to left and right. Range from -180 to 180
      Yaw: 0.0
    FlyLandLocation:
      # Used when players fly state is being turned to false because of fly flag and there is no solid land where to land for player
      World: survival
      X: 0.5
      Y: 63.0
      Z: 0.5
      # Less than 0 - head up, more than 0 - head down. Range from -90 to 90
      Pitch: 0.0
      # Head position to left and right. Range from -180 to 180
      Yaw: 0.0
```

**To Reproduce**
This locations are defined in the config, but its not working properly, because when the player enters a residence, which has move false, he is teleported back to different world and location, when he was before, which could be for example event, mobarena, etc....

**Server version:**
3:18:01[INFO] Residence version: 5.1.6.5
13:18:01[INFO] CMILib version: 1.5.2.9
13:18:01[INFO] Java version: 21.0.2
