### ISSUE TITLE
Residence groups doesn't work

### ISSUE THREAD

**Issue by PriestOfTerror** [Zrips/Residence#1266]
Hi,
I have set up groups default, NextGroup and VIP
I added residence.group.nextgroup to luckyperms and I also tried residence.group.vip because they are the same. But neither one works, I have width and length limits in both groups 150 and number of residences 5, but it says 0.
What is wrong? 

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/099e5ef0-c8a0-4738-a887-ab96d75d82b2" />

https://pastebin.com/XQWkrgeh

**Comment by Zrips** [comment]
Text format in your groups file was incorrect, quite few mistakes with text alignment. Suggestion would be to check console for any reported error messages when reloading or loading server which will indicate any issues it will encounter.
Correct format would have looked like this
```
# These groups correspond to the Permissions groups defined in your '<worldname>.yml'
Groups:
  Default: # group name, DONT remove this group
    # Information about the Residence zone that the player can define.
    # Uncomment the lines below to mirror this config to other groups.
    # Mirror:
    #   - 'group1'
    #   - 'group2'
    Residence:
      # Determines if this group can create residences or not. This option can be overridden with the permissions node 'residence.create'
      CanCreate: true
      # The maximum number of Residences a player can have.
      MaxResidences: 3
      # The maximum number of physical areas a residence can have.
      MaxAreasPerResidence: 2
      # The maximum number of blocks a Residence can be, East to West (X).
      MaxEastWest: 50
      # (Optional) The minimum number of blocks a Residence can be, East to West (X).
      MinEastWest: 3
      # The maximum number of blocks a Residence can be, North to South (Z).
      MaxNorthSouth: 50
      # (Optional) The minimum number of blocks a Residence can be, North to South (Z).
      MinNorthSouth: 3
      # The maximum number of blocks a Residence can be, High to Low (Y).
      MaxUpDown: 320
      # (Optional) The minimum number of blocks a Residence can be, High to Low (Y).
      MinUpDown: 3
      # The lowest altitude this group is allowed to protect.
      MinHeight: -64
      # The highest altitude this group is allowed to protect.
      MaxHeight: 320
      # The maximum amount of subzones a current area can have.
      MaxSubzonesInArea: 3
      # The maximum recursive depth that subzones can go.
      # A subzone within a subzone within the Residence zone would be a depth of 2.
      # Set to 0 to disable subzones.
      SubzoneDepth: 3
      # (Optional) The maximum number of blocks a Residence Subzone can be, East to West (X).
      SubzoneMaxEastWest: 16
      # (Optional) The minimum number of blocks a Residence Subzone can be, East to West (X).
      SubzoneMinEastWest: 3
      # (Optional) The maximum number of blocks a Residence Subzone can be, North to South (Z).
      SubzoneMaxNorthSouth: 16
      # (Optional) The minimum number of blocks a Residence Subzone can be, North to South (Z).
      SubzoneMinNorthSouth: 3
      # (Optional) The maximum number of blocks a Residence Subzone can be, High to Low (Y).
      SubzoneMaxUpDown: 320
      # (Optional) The minimum number of blocks a Residence Subzone can be, High to Low (Y).
      SubzoneMinUpDown: 3
      # Whether or not to allow teleporting to Residences.
      CanTeleport: true
      # Allow or disallow the use of /res unstuck, to get yourself out of a residence if stuck in one somehow.
      Unstuck: true
      # Allow or disallow the use of /res kick, to kick player from residence.
      Kick: false
      # Allow or disallow the use of the /res select command.
      SelectCommandAccess: true
      # Allow or disallow the group to access the Blacklist/Ignorelist for residences they own.
      ItemListAccess: true

    # Options relating to enter and leave messages on the residence.
    Messaging:
      # Whether or not the player can change the Residence enter and leave messages.
      CanChange: true
      # Default enter message.
      DefaultEnter: "Welcome %player to %residence, owned by %owner."
      # Default leave message.
      DefaultLeave: "Now leaving %residence."

    # Options relating to the Lease system.
    Lease:
      MaxDays: 16
      RenewIncrement: 14

    # Options related to the rent system.
    Rent:
      MaxRents: 3
      MaxRentables: 3
      MaxRentDays: 31

    # Options relating to the Residence Economy.
    Economy:
      CanBuy: true
      CanSell: false
      IgnoreLimits: false
      BuyCost: 0.5
      SellCost: 0.25
      RenewCost: 0.2

    # Flags settings override global flags.
    Flags:
      Permission:
        # build: true
      Default:
        # build: true
      CreatorDefault:
        # build: true
      GroupDefault:
        # default: # group name
          # build: false
      World:
        Global:
          # build: false
        WorldNameHere:
          # build: false

  NextGroup:
    Residence:
      CanCreate: true
      MaxResidences: 5
      MaxAreasPerResidence: 3
      MaxEastWest: 150
      MaxNorthSouth: 150
      MaxUpDown: 20
      MinHeight: -64
      MaxHeight: 320
      SubzoneDepth: 3
      CanTeleport: true
      Unstuck: true
      Kick: true
      SelectCommandAccess: true
      ItemListAccess: true
    Messaging:
      CanChange: true
      DefaultEnter: "Welcome %player to %residence, owned by %owner."
      DefaultLeave: "Now leaving %residence."
    Lease:
      MaxDays: 16
      RenewIncrement: 14
    Rent:
      MaxRents: 3
      MaxRentables: 3
      MaxRentDays: 31
    Economy:
      CanBuy: true
      CanSell: false
      IgnoreLimits: false
      BuyCost: 0.3
      SellCost: 0.25
      RenewCost: 0.3

  VIP:
    Residence:
      CanCreate: true
      MaxResidences: 5
      MaxAreasPerResidence: 3
      MaxEastWest: 150
      MaxNorthSouth: 150
      MaxUpDown: 20
      MinHeight: -64
      MaxHeight: 320
      SubzoneDepth: 3
      CanTeleport: true
      Unstuck: true
      Kick: true
      SelectCommandAccess: true
      ItemListAccess: true
    Messaging:
      CanChange: true
      DefaultEnter: "Welcome %player to %residence, owned by %owner."
      DefaultLeave: "Now leaving %residence."
    Lease:
      MaxDays: 16
      RenewIncrement: 14
    Rent:
      MaxRents: 3
      MaxRentables: 3
      MaxRentDays: 31
    Economy:
      CanBuy: true
      CanSell: false
      IgnoreLimits: false
      BuyCost: 0.3
      SellCost: 0.25
      RenewCost: 0.3

# You can manually specify the group a player is in below; this overrides their permissions group.
GroupAssignments:
  bekvon: Default
  player: Default

```
