### ISSUE TITLE
Subzone flags not working as expected

### ISSUE THREAD

**Issue by austinhuang0131** [Zrips/Residence#23]
Let's say I built a public marketplace where each player can get a stall to sell their items. The marketplace cannot be griefed so I claimed the whole marketplace, then I make little stalls and give them to the players. Now these players have ownership of the subzone but still cannot do things (build/container/destroy, I have checked `/res info` and they have flags). Is that a UUID conversion problem?

First several lines of my config:
```yaml
# These are Global Settings for Residence.
Global:
  # Starts UUID conversion on plugin startup
  # DONT change this if you are not sure what you doing
  UUIDConvertion: false
  # If you running offline server, better to check this as true. This will help to solve issues with changing players UUID.
  OfflineMode: true
```

I am 1.11.2 Spigot and I am running offline mode.
