### ISSUE TITLE
{residence} placeholder not working in CMI

### ISSUE THREAD

**Issue by Mrs-Feathers** [Zrips/Residence#241]
CMI config:

```
  GeneralFormat: '&7[&f%multiverse_world_name_colored%&7][&b{residence}&7][%luckperms_prefix%&7]&r{displayName}&7»
    &r{message}'
```

Reisdence Config:

```
    GlobalChat:
      # Enables or disables chat modification by including players main residence name
      Enabled: true
      # Modifys chat to add chat titles.  If you're using a chat manager, you may add the tag {residence} to your chat format and disable this.
      SelfModify: false
      Format: '&c[&e%1&c]'
```

Version Info:
![screen shot 2018-12-29 at 20 24 43](https://user-images.githubusercontent.com/1746550/50543483-cb506b80-0ba7-11e9-8327-b1f1ac8638b6.png)

Problem:
![screen shot 2018-12-29 at 20 26 16](https://user-images.githubusercontent.com/1746550/50543494-0f437080-0ba8-11e9-9c19-ab52fbd15bcc.png)
