### ISSUE TITLE
Server restart needed to make effective Residence changes

### ISSUE THREAD

**Issue by WyRe** [Zrips/Residence#30]
I'm coming from there https://github.com/bekvon/Residence/issues/132

**Comment by WyRe** [comment]
The point is I need restar my Spigot server to make effective the flags in the protected region, I mean the plugin works so fine, but if I don't restart the server the flags are not applying in the protected region.

**Comment by Zrips** [comment]
Which particular flags or all of them? What you mean that if you don't restart server flags are not applying?

**Comment by WyRe** [comment]
I've setup the same flags to all residences in the server and owners have got disabled `admin` flag, when somebody protects a region using Residence, the `build` flag (most important flag) is not being applied, I mean, others players can build inside his region, I need to restart the server to do effective the protection.

**Comment by Zrips** [comment]
Double check your flags.yml and check if your ResidenceDefault flag section is set correctly. It should look something like this
`
  ResidenceDefault:
    build: false
    use: false
    monsters: true
    container: false
    pvp: false
    tnt: false
    creeper: false
    diode: true
    piston: true
    ignite: false
    firespread: false
    tp: false
    move: false
    flow: false
    vehicledestroy: false
    animalkilling: false
    shear: false
    leash: false`
and CreatorDefault should look something like 
`
  CreatorDefault:
    build: true
    move: true
    use: true
    riding: true
    ignite: true
    container: true
    tp: true
    flow: true
    diode: true
    piston: true
    animalkilling: true
    mobkilling: true
    vehicledestroy: true
    trade: true
    shear: true
    leash: true`

**Comment by WyRe** [comment]
That's my `flags.yml` content according to that, I think it's right:

```
  ResidenceDefault:
    build: false
    use: true
    container: true
    pvp: true
    tnt: true
    creeper: false
    flow: true
    piston: true
    ignite: true
    firespread: true
    vehicledestroy: true
    animalkilling: true
    shear: true
    leash: true
    tp: true
    door: true
  CreatorDefault:
    bank: true
    admin: false
    build: true
    move: true
    use: true
    ignite: true
    container: true
    animalkilling: true
    mobkilling: true
    vehicledestroy: true
    trade: true
    shear: true
    leash: true
```
