### ISSUE TITLE
Residence group inheritance (mirror) not working 

### ISSUE THREAD

**Issue by Iwitrag** [Zrips/Residence#347]
Residence version 4.8.6.6

Hi, residence group mirroring is not working. I'm using LuckPerms.

My groups:
default
player
vip

Player inherits from default, VIP inherits from Player.
VIP has permission residence.group.vip.

I want to allow VIP to create more residences and larger. So I have mirrored default config to VIP and changed only size and amount of residences... but it's not working.

VIP is not able to create residences at all. No configs are mirrored.

/res limits says:
- permission group: vip
- residence group: vip
- can create residence: false

My config:
```
# These groups correspond to the Permissions groups defined in your '<worldname>.yml'
Groups:
    Default: #group name, DONT remove this group
       # Information about the Residence zone that the player can define.
       #Uncomment the lines below to mirror this config to other groups.
       Mirror:
         - 'player'
         - 'vip'
       Residence:
           # Determins if this group can create residences or not.  This option can be overriden with the permissions node 'residence.create'
           CanCreate: true
           # The maximum number of Residences a player can have.
           MaxResidences: 3
           # The maximum number of physical areas a residence can have.
           MaxAreasPerResidence: 1
           # The maximum number of blocks a Residence can be, East to West (X).
           MaxEastWest: 50
           # (Optional) The minimum number of blocks a Residence can be, East to West (X).
           MinEastWest: 3
           # The maximum number of blocks a Residence can be, North to South (Z).
           MaxNorthSouth: 50
           # (Optional) The minimum number of blocks a Residence can be, North to South (Z).
           MinNorthSouth: 3
           # The maximum number of blocks a Residence can be, High to Low (Y).
           MaxUpDown: 256
           # (Optional) The minimum number of blocks a Residence can be, High to Low (Y).
           MinUpDown: 3
           # The lowest altitude this group is allowed to protect.
           MinHeight: 0
           # The highest altitude this group is allowed to protect.
           MaxHeight: 255
            # The maximum amount of subzones can current area have.
           MaxSubzonesInArea: 10
            # The maximum recursive depth that subzones can go.
            # A subzone within a subzone within the Residence zone would be a depth of 2.
            # Set to 0 to disable subzones.
           SubzoneDepth: 1
           # (Optional) The maximum number of blocks a Residence Subzone can be, East to West (X).
           SubzoneMaxEastWest: 50
           # (Optional) The minimum number of blocks a Residence Subzone can be, East to West (X).
           SubzoneMinEastWest: 3
           # (Optional) The maximum number of blocks a Residence Subzone can be, North to South (Z).
           SubzoneMaxNorthSouth: 50
           # (Optional) The minimum number of blocks a Residence Subzone can be, North to South (Z).
           SubzoneMinNorthSouth: 3
           # (Optional) The maximum number of blocks a Residence Subzone can be, High to Low (Y).
           SubzoneMaxUpDown: 256
           # (Optional) The minimum number of blocks a Residence Subzone can be, High to Low (Y).
           SubzoneMinUpDown: 3
           # Whether or not to allow teleporting to Residences.
           CanTeleport: false
           # Allow or Disallow the use of /res unstuck, to get yourself out of a residence if stuck in one somehow
           Unstuck: false
           # Allow or Disallow the use of /res kick, to kick player from residence.
           Kick: true
           # Allow or Disallow the use of the /res select command, if disabled they can only use the selection tool.
           SelectCommandAccess: true
           # Allow or Disallow the group to access the Blacklist/Ignorelist for residences they own.
           ItemListAccess: false
       # Options relating to enter and leave messages on the residence.
       Messaging:
           # Whether or not the player can change the Residence enter and leave messages.
           CanChange: false
           # The default enter message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultEnter: "--- Vstupuješ do rezidence %residence hráče %owner ---"
           # The default leave message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultLeave: "--- Opouštíš rezidenci %residence ---"
       # Options relating to the Lease system.
       Lease:
          # The maximum number of days to allow leases.
          MaxDays: 16
          # The number of days to add to the lease following a '/res lease renew' command.
          RenewIncrement: 14
       #Options related to the rent system
       Rent:
           #determines how many residences can be rented by players of this group at once
           MaxRents: 3
           #determines how many residences can be set for rent by players of this group at once
           MaxRentables: 3
           # determines max days player can rent residence at once
           MaxRentDays: 31
       # Options relating to the Residence Economy.
       Economy:
          # Whether or not players in this group can buy other Residences that are for sale.
          CanBuy: false
          # Whether or not players in this group can sell their Residences.
          CanSell: false
          # Whether or not to ignore the Residence size/count limits when buying a residence.
          IgnoreLimits: false
          # The cost, per block, of making a new Residence or adding a area to it.
          BuyCost: 0.5
          # The cost, per block, player will be getting back when removing residence.
          SellCost: 0.25
          # The cost, per block, of renewing a Residence lease (if the lease system is enabled).
          RenewCost: 0.2
       # Flags are checked in the order:
       # 1: Player
       # 2: Group
       # 3: Owner
       # 4: If all others are undefined, reverts to default value (usually true).
       # Flag permissions default to false.
       # These flags settings override the globals.
       Flags:
          # Specifically allow or deny this group from changing certain flags.
          Permission:
               #build: true
          # Specifys the flags that are applied at residence creation for players of this group.
          Default:
              #build: true
          # Specifys the flags that are applied at to the creator at residence creation.
          CreatorDefault:
              #build: true
          # Specifys the flags that are applied to other groups for this residence, at creation.
          GroupDefault:
               #default: #group name
                   #build: false
          #these flags are applied specifically to this group whenever they are outside a residence
          #these flags will override the flags at the top, under the Global section.
          World:
                Global: #these flags will apply to all worlds
                     #build: false
                #WorldNameHere: #or you can apply them by each individual world
                     #build: false
    vip: #group name, player should have residence.group.nextgroup permission node to have access to this residence group
       Residence:
           MaxResidences: 5
           MaxEastWest: 75
           MaxNorthSouth: 75
           SubzoneMaxEastWest: 75
           SubzoneMaxNorthSouth: 75

# You can manually specify the group a player is in below, this overrides their permissions group.
GroupAssignments: []
```
