### ISSUE TITLE
Config.yml - Global.Selection.IgnoreY: true (But it is 0 - 254) V:4.8.8.2

### ISSUE THREAD

**Issue by Saukiya** [Zrips/Residence#399]
(My English is not good)
My groups.yml is this:
```
Groups:
    Default: 
       Residence:
          # ignore up
          MaxUpDown: 256
          MinUpDown: 3
          MinHeight: 0
          MaxHeight: 256
          # ignore down
```
When using IgnoreY true, it create Y:0 to 254 residence, No restriction on the 255 block cell.
hope fix, Thankyou

My Residence Version: 4.8.8.2
