### ISSUE TITLE
Random Teleportation

### ISSUE THREAD

**Issue by matbcvo** [Zrips/Residence#499]
Picture: https://i.imgur.com/3QuwpAX.png
MinCoord is 1000 and MaxCoord is 5000, yet it still teleports to X/Y less than 1000 and never more than 1000.

```
      world:
        Enabled: true
        MaxCoord: 5000
        MinCoord: 1000
        CenterX: 0
        CenterZ: 0
```

Default values were MaxCoord 1000 and MinCoord 500.

Residence version: 4.9.1.1
Paper version: 1.6.1 build 34

**Comment by corwinbass** [comment]
same problem here. when i add another world to that list and set MaxCoord to 5000 (any value), it either gets strait deleted from config (on server start or after using /resadmin reload config), or replaced with default values(min 500, max 1000).

**Comment by Zrips** [comment]
ecff72e07392af1b6d0de1cacc775d641290d131

**Comment by matbcvo** [comment]
Still not fixed. Using Residence 4.9.1.3 right now.

![image](https://user-images.githubusercontent.com/1006437/87329190-3de12c00-c53f-11ea-9052-cff232484d83.png)

```
      world:
        Enabled: true
        MaxCoord: 5000
        MinCoord: 1000
        CenterX: 0
        CenterZ: 0
```
