### ISSUE TITLE
[Feature request] - Newcommer's residence - free option for /res create/auto

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#544]
Hi, for now we can set this for new player:
```
  NewPlayer:
    Use: true
    # Setting this to true, residence will be created for free
    # By setting to false, money will be taken from player, if he has them
    Free: true
    # Range from placed chest o both sides. By setting to 5, residence will be 5+5+1 = 11 blocks wide
    Range:
      X: 50
      Y: 255
      Z: 50
```

But when we set it free, it only applies for chest range.... but what when we wanna make his residence free even if he will create it using /res create or /res auto?

And also be nice, if there's option to make his first residence bigger, yes, there's range, but it's still just for chest.... what about when we want to make his residence created via selection tool and /res create, or /res auto, bigger too by this range?

Will be glad if you could make these two improvements to newplayer. Maybe there can be just one option:
```
  NewPlayer:
    Use: true
    # Setting this to true, residence will be created for free
    # By setting to false, money will be taken from player, if he has them
    Free: true
    # Range from placed chest o both sides. By setting to 5, residence will be 5+5+1 = 11 blocks wide
    Range:
      X: 50
      Y: 255
      Z: 50
    Apply_for_normal_creation: true
```
that will aply free and range (both of them), so he can create residence 101*101, even if he has permission (limit) to create residence just 60*60. And this first residence created also via /res create or /res auto will be free too!
