### ISSUE TITLE
AutoCleanUp - way to give deleted residence to player with specific name (or execute command)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#608]
```
  AutoCleanUp:
    # HIGHLY EXPERIMENTAL residence cleaning on server startup if player is offline for x days.
    # Players can bypass this with residence.cleanbypass permission node
    Use: true
    # For how long player should be offline to delete hes residence
    Days: 30
    # Do you want to regenerate old residence area
    # This requires world edit to be present
    Regenerate: true
    # Worlds to be included in check list
    Worlds:
    - world
```

Hi, could you add way to add command on deletion instead of deletion, so for ex. we can set there that after 30 days of inactivity will be residence added to server account and then we can make auction about this residence?
