### ISSUE TITLE
customcontainers and mod support

### ISSUE THREAD

**Issue by MSTRBTL** [Zrips/Residence#692]
Hello,
I´m have problem with CustomContainers and with anything about mod support. 

Nowhere did I find how to write it correctly, is it like this?
I use the latest version of residence.

```
  CustomContainers:
  - 5836
  CustomBothClick: []
  CustomRightClick:
  - 5836
```
  
  Thank you for help.
