### ISSUE TITLE
auto clean up does not work

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#714]
I have already set true to use the AutoCleanUpfunction.
I have used seen function to check the last logout time of a player.
The player was offline 2 months ago,
However, his residence is not deleted. by the function of AutoCleanUp,
The server log shows that the 0 residences are deleted.

`[Server thread/INFO]: [Residence] Auto CleanUp deleted 0 residences!`

```
  AutoCleanUp:
    # HIGHLY EXPERIMENTAL residence cleaning on server startup if player is offline for x days.
    # Players can bypass this with residence.cleanbypass permission node
    Use: true
    # For how long player should be offline to delete hes residence
    Days: 60
    # Do you want to regenerate old residence area
    # This requires world edit to be present
    Regenerate: false
    # Worlds to be included in check list
    Worlds:
    - Survival_world
    
```
