### ISSUE TITLE
Wrongly written character in config.yml

### ISSUE THREAD

**Issue by aianlinb** [Zrips/Residence#73]
```
# These are Global Settings for Residence.
Global:
  # Starts UUID conversion on plugin startup
  # DONT change this if you are not sure what you doing
  UUIDConvertion: false
  # If you running offline server, better to check this as true. This will help to solve issues with changing players UUID.
  OfflineMode: true
  # Players with residence.versioncheck permission node will be noticed about new residence version on login
  versionCheck: true
  # This loads the <language>.yml file in the Residence Language folder
  # All Residence text comes from this file. (NOT DONE YET)
  Language: ChineseTW
  # Wooden Hoe is the default selection tool for Residence.
  # You can change it to another item ID listed here: http://www.minecraftwiki.net/wiki/Data_values
  SelectionToolId: 280
  Selection:
    # By setting this to true, all selections will be made from bedrock to sky ignoring Y coordinates
    IgnoreY: false
    # By setting this to true, player will only pay for x*z blocks ignoring height
    # This will lower residence price by up to 256 times, so ajust block price BEFORE enabling this
                                           ajust --> adjust  ^^^^^
```
