### ISSUE TITLE
Disable building outside residence (Global Flag Group Override not Working)

### ISSUE THREAD

**Issue by AdamValach** [Zrips/Residence#731]
Hi,
I am trying to achieve that the default group is not able to build outside residences. 
For this usecase the _Global->Flags->Global_ section in flags.yml exists.

Showcase (_Global->Flags->Global_ section of flags.yml):

```
# These are Global Settings for Residence.
Global:
  # These are world flags that are applied when the player is NOT within a residence.
  Flags:
    # these are default for all worlds unless specified below, they can be overridden per group
    Global:
      use: true
      build: true
      ignite: true
      firespread: true
      damage: true
      creeper: true
      nmonsters: true
      tnt: true
      pvp: true
  # This gives permission to change certain flags to all groups, unless specifically denied to the group.
  FlagPermission:
```

When I am attempting to bypass these settings in the groups.yml for the default group using the _Groups->Default->Flags->World_ section these **settings get ignored**.

Showcase _Groups->Default->Flags_ section of groups.yml)

```
       Flags:
          # Specifically allow or deny this group from changing certain flags.
          Permission:
               #build: true
          # Specifys the flags that are applied at residence creation for players of this group.
          Default:
              #build: true
          # Specifys the flags that are applied at to the creator at residence creation.
          CreatorDefault:
              #build: true
          # Specifys the flags that are applied to other groups for this residence, at creation.
          GroupDefault:
               #default: #group name
                   #build: false
          #these flags are applied specifically to this group whenever they are outside a residence
          World:
                Global: #these flags will apply to all worlds
                     build: false
                     destroy: false
                WorldNameHere: #or you can apply them by each individual world
                     #build: false
```

Flags.yml is practically unedited. Groups.yml has added 3 player groups (which I had no problems with so far, should be unrelated to this issue)

Residence version: 4.9.3.10
Server: Paper 1.16.5
flags.yml - https://pastebin.com/LYBpVwMA
groups.yml - https://pastebin.com/pKggamix
