### ISSUE TITLE
Permission `residence.randomtp: false` not working in 4.7.0.4

### ISSUE THREAD

**Issue by shikendon** [Zrips/Residence#80]
I am trying to disable `/res rt` command in my `permission.yml`:
```yaml
server.basics:
  description: Basic permissions for My Cool Server.
  default: true
  children:
    residence.randomtp: false
```

It works in 4.7.0.3 but not in 4.7.0.4. Is there anything I should change or it's a bug?
