### ISSUE TITLE
Residence Enter/Leave Message Bug(?)

### ISSUE THREAD

**Issue by D3thw0lf** [Zrips/Residence#85]
![2017-07-27_12 35 55](https://user-images.githubusercontent.com/895448/28666646-8d5f2b28-72c8-11e7-8133-49d91bb59736.png)
This always appears even if the following booleans are set to false in Config File:
```yaml
  ActionBar:
    # True for ActionBar - new component in 1.8
    # False for old Messaging in chat enter/leave Residence messages
    General: false
    ShowOnSelection: false
  TitleBar:
    # When set to true enter/leave messages will be shown in title/subtitle slots
    # Subtitle can be defined with %subtitle% while setting enter/leave messages
    EnterLeave: false
```
Did I missed something in config?

Version (Spigot):
Spigot 1.9.4 (git-Spigot-c6871e2-0cd0397)

Version (PlugIn):
Residence 4.7.1.1
