### ISSUE TITLE
Can't change NewPlayer free residence setting when ignoreY is enabled.

### ISSUE THREAD

**Issue by smartmadio** [Zrips/Residence#861]
New players still get 3×3 residence when putting container on ground with these settings below:(If I turn 'IgnoreY' to 'false',then the new player can get 33×33 residence.)
The config.yml setting:
```
  NewPlayer:
    Use: true
    # Setting this to true, residence will be created for free
    # By setting to false, money will be taken from player, if he has them
    Free: true
    # Range from placed chest o both sides. By setting to 5, residence will be 5+5+1 = 11 blocks wide
    Range:
      X: 16
      Y: 384
      Z: 16
```

```
  Selection:
    # By setting this to true, all selections will be made from bedrock to sky ignoring Y coordinates
    IgnoreY: true
    # When this set to true, selections inside existing residence will be from bottom to top of that residence
    # When this set to false, selections inside existing residence will be exactly as they are
    IgnoreYInSubzone: false
    # Defines height of nether when creating residences. This mostly applies when performing commands like /res select vert or /res auto which will expand residence to defined height
    # This cant be higher than 319 or lower than 1
    netherHeight: 128
    # By setting this to true, player will only pay for x*z blocks ignoring height
    # This will lower residence price by up to 319 times, so adjust block price BEFORE enabling this
    NoCostForYBlocks: true
```

### Server info:
Paperspigot 1.18.1 
Residence 5.0.1.3
