### ISSUE TITLE
Some ResidenceDefault flags are not overwritable

### ISSUE THREAD

**Issue by augstb** [Zrips/Residence#885]
I use latest version ```5.0.1.6```.
After a relatively recent update, I saw some default flags (set to false) were added at residence creation.
It concerns :
- nanimals
- sanimals
- monsters
- nmonsters
- smonsters
- monsters
- iceform
- icemelt
- pvp (not sure about this one)

I want to keep mob spawning with default minecraft values on residence creation. So here is my config (in flags.yml) :
```yml
  ResidenceDefault:
    flow: true
    iceform: true
    nanimals: true
    sanimals: true
    monsters: true
    icemelt: true
    nmonsters: true
    smonsters: true
    container: false
    shear: false
    use: false
    destroy: false
    pvp: false
    animalkilling: false
    hook: false
    build: false
    vehicledestroy: false
    leash: false
```
After a restart (the /resadmin reload config does not reload ```ResidenceDefault``` values btw), and after created a new residence, here are the flags of the residence :
![Residence flags](https://www.stillcraft.fr/files/residence_flags.jpg)

Among all the ```true``` flags I set, only the flow worked (I added it for the test). Global flags only contains ```use``` and ```build``` set to ```true```.
I didn't found any way to set these flags to ```true``` on creation. I can however remove the flags by hand afterwards.

Thank you for your feedback !
