### ISSUE TITLE
enhancement - AutoCleanUp - separation of functions

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#932]
Hi, the AutoCleanUp config currently looks like this: 
```
    AutoCleanUp:
    Use: true
    Days: 152
    Regenerate: false
    Worlds:
    - world
    - world_the_end
    - world_nether
```

I would also like to turn on regeneration, but I have a custom map on the server that I made through WorldPainter, so regeneration would destroy my own terrain and replace it with the basic one. So my idea is if it would be possible to separate the deletion and regeneration functions - worlds in which it would only delete the residence and worlds in which it would also regenerate the terrain would be listed. I hope it is at least a little understandable
